version: 2.1
# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: circleci/python:3.7.4
    steps:
      - checkout
      - run:
          name: Setup virtualenv
          command: python3 -m venv venv && source venv/bin/activate
      - run:
          name: Install dependencies
          command: pip install -e .
      - run:
          name: Run pylint
          command: python -m pylint src
      - run:
          name: Run pytest without cache plugin
          command: python -m pytest src -p no:cacheprovider
# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build